// Daily quotes for your game — rotate automatically based on day of year
const DAILY_QUOTES = [
  "The expert in anything was once a beginner. – Helen Hayes",
  "Your career doesn’t define you—but your curiosity does. – Anonymous",
  "Build the skills. Ship the projects. Get the job. – Developer Mantra",
  "Cloud is not just technology—it’s opportunity. – You, soon.",
  "Every line of code is a step toward your new career. – Anonymous",
  "Don’t wait for the perfect moment. Deploy anyway. – DevOps Wisdom",
  "From pipes to pipelines—you’ve got this. – To all career changers",
  "Infrastructure as Code is your resume. – Cloud Engineer Proverb",
  "Progress > perfection. Especially on Day 1. – Terraform Truth",
  "You don’t need permission to build something real. – Indie Hacker",
  "The best time to learn AWS was 2 years ago. The second best time is today. – Cloud Proverb",
  "Automation is the friend of the career changer. – You, soon.",
  "A portfolio beats a PowerPoint any day. – Hiring Manager",
  "GitHub is the new resume. – Tech Recruiter",
  "Learn in public. Build in public. Get hired in public. – #100Devs",
  "Cost optimization starts with architecture—and ends with a paycheck. – Cloud Architect",
  "Serverless doesn’t mean stress-less—but it’s close. – AWS Dev",
  "Your past experience is your superpower—not a limitation. – Career Coach",
  "The cloud welcomes all—especially those willing to learn. – AWS Community",
  "One project today > ten plans tomorrow. – Builder’s Creed",
  "Debug your fears like you debug your code. – Developer Mindset",
  "You belong here—even if your last job was with wrenches, not wires. – Tech Community",
  "Terraform apply your confidence. – DevOps Affirmation",
  "Great engineers aren’t born—they’re built, one commit at a time. – Anonymous",
  "The future is self-taught. – Online Learner",
  "Cloud skills = leverage. Use it. – Career Strategist",
  "Done is better than perfect—especially on GitHub. – Ship It!",
  "Your first PR is the hardest. Your 10th gets you hired. – Open Source Truth",
  "S3 stores files. GitHub stores your future. – Cloud Dev",
  "Keep going. The job post you’ll get is already written. – Future You"
];
